module RealLifeShared
{
    export enum EnmVehicleComponente
    {
        SPOILERS = 0,
        FRONT_BUMPER = 1,
        REAR_BUMPER = 2,
        SIDE_SKIRT = 3,
        EXHAUST = 4,
        FRAME = 5,
        GRILLE = 6,
        HOOD = 7,
        FENDER = 8,
        RIGHT_FENDER = 9,
        ROOF = 10,
        ENGINE = 11,
        BRAKES = 12,
        TRANSMISSION = 13,
        HORNS = 14,
        SUSPENSION = 15,
        ARMOR = 16,
        TURBO = 18,
        XENON = 22,
        FRONT_WHEELS = 23,
        BACK_WHEELS = 24,
        PLATE_HOLDERS = 25,
        TRIM_DESIGN = 27,
        ORNAMENTS = 28,
        DIAL_DESIGN = 30,
        STEERING_WHEEL = 33,
        SHIFT_LEVER = 34,
        PLAQUES = 35,
        HYDRAULICS = 38,
        LIVERY = 48,
        PLATE = 62,
        COLOUR_1 = 66,
        COLOUR_2 = 67,
        WINDOW_TINT = 69,
    }
}